variables:
    # domain/project-registry/project-gitlab:tag_commit
    #registry.huancd.name.vn/devops/shoeshop:v0.0.1_3gej3h13
    DOCKER_IMAGE: ${REGISTRY_URL}/${REGISTRY_PROJECT}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}
    DOCKER_CONTAINER: ${CI_PROJECT_NAME}

stages:
    - buildandpush
    - deploy
    - showlog

build:
    stage: buildandpush
    variables:
        GIT_STRATEGY: clone
    #login vao registry
    before_script:
        - docker login ${REGISTRY_URL} -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}

    script:
        - docker build -t $DOCKER_IMAGE .
        - docker push $DOCKER_IMAGE
    tags:
        - dev-server
    only:
        - tags

deploy:
    stage: deploy
    variables:
        GIT_STRATEGY: none
    when: manual
    before_script:
        - docker login ${REGISTRY_URL} -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
    script:
        - docker pull $DOCKER_IMAGE
        - docker rm -f $DOCKER_CONTAINER
        - docker run --name $DOCKER_CONTAINER -dp 8080:8080 $DOCKER_IMAGE

    tags:
        - dev-server
    only:
        - tags

showlog:
    stage: showlog
    variables:
        GIT_STRATEGY: none
    when: manual

    script:
        - sleep 30
        - docker logs $DOCKER_CONTAINER

    
    tags:
        - dev-server
    only:
        - tags
